### ISSUE TITLE
OAuth2를 이용한 로그인 구현

### ISSUE THREAD

**Issue by migusdn** [DeveloperAcademy-POSTECH/2HoSeon-Server#1]
📌 Issue

- OAuth2를 이용하여 SNS 로그인을 구현합니다.
- Frontend 에서 발급받은 Authorization Code를 사용하여 OAuth2 인증을 수행하고 접근 가능한 JWT Token을 발급합니다.

## 📸 ScreenShot

|기능|스크린샷|
|:--:|:--:|
|Sign in with Apple|<img src = "https://docs-assets.developer.apple.com/published/1d16867b5d/sign-in-with-apple-2@2x.png">

## 📝 To-do

- [x] Apple Login
- [ ] Google Login (option)
- [ ] Naver Login (option)
- [ ] Kakao Login (option)
- [x] JWT Token Authentication
