### ISSUE TITLE
Profile Setting 추가

### ISSUE THREAD

**Issue by pingse** [DeveloperAcademy-POSTECH/2HoSeon-Server#8]
📌 Issue

<!- 이슈에 대해 간략하게 설명해주세요 -> 
- 추가할 필드를 Member에 추가하고 ProfileRequestDTO 작성

## 📝 To-do
<!- 진행할 작업에 대해 적어주세요 ->
- [x] 각종 필드 추가
- [x] ProfileRequestDTO 추가
- [x] School 객체 추가
- [x] MemberRestController 추가
- [x] 프로필 세팅, 닉네임 중복 확인 로직 추가
